title: InvestSavy
email: investsavy-oficial.support@gmail.com
description: Transformando sua vida financeira
baseurl: ''
url: ''

# Build settings
theme: minima
markdown: kramdown
permalink: /news/:year/:month/:day/:title/

# Collections
collections:
  posts:
    output: true
    permalink: /news/:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
      author: 'InvestSavy'

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .gitignore
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
